### ISSUE TITLE
Question about convert()

### ISSUE THREAD

**Issue by MesSem** [NotWoods/spherical-geometry-js#24]
Hi, in the convert function in [latlng.js](https://github.com/NotWoods/spherical-geometry-js/blob/master/src/latlng.js) you convert an array of two number with this code 
`return new Class(like[1], like[0]);`
why you choose to take the first as longitude and the second as latitude. Usually the latitude is the first and longitude the second, is counterintuitive. Is there a motivation?

**Comment by NotWoods** [comment]
I wrote it that way to match [GeoJSON positions](https://tools.ietf.org/html/rfc7946#section-3.1.1), which represent points as `[long, lat]` as it corresponds to a global `[x, y]`. 

If you represent points at `[lat, long]` in your code I would recommend converting it to an object literal like `{ lat, long }` before calling the spherical-geometry-js functions.

**Comment by MesSem** [comment]
Ok, thank you for the clarification.
