### ISSUE TITLE
Compute center of multiple coordinates

### ISSUE THREAD

**Issue by dcts** [NotWoods/spherical-geometry-js#96]
Is there a way of computing the center of multiple geolocations (specified as long lat objects) with this library? I could not find anything in the files and didnt see documentation for this. 

Thanks!

**Comment by NotWoods** [comment]
Does `LatLngBounds().getCenter()` work for you? [See Google Maps usage here](https://stackoverflow.com/a/27601389/3762168)

**Comment by dcts** [comment]
Thanks a lot, this worked for me! Heres my code if anyone has the same issue:

```javascript
import { LatLng, LatLngBounds } from 'spherical-geometry-js';

const bounds = new LatLngBounds();
allCoordinates.forEach(coordinate => {
  bounds.extend(new LatLng(coordinate.lat, coordinate.lng));
})
const centerLatLng = bounds.getCenter();
console.log(centerLatLng.toString());
```

**Comment by dcts** [comment]
@NotWoods just tried to send you an email to contact@tigeroakes.com but my mail client says the address is invalid. Is this address not in use?
